### ISSUE TITLE
Alternative Images don't show up when system doesn't use the foundry standard

### ISSUE THREAD

**Issue by BokuNC** [Zombiefleischer/pause-text#30]
As it is, right now, if the system includes a custom pause image or config, the module isn't capable of changing it at all.

For example, World of Darkness 5e and World of Darkness 20th Anniversary both have this problem.

There does seem to be a pull request that tries to solve this issue, but its still open to this day.

**Comment by Zombiefleischer** [comment]
The pull request is only a refactoring of code, nothing that solves the problem. Also, I try to maintain this module in my spare free time, with limited JavaScript knowledge as a hobby project, so bare with me, if it sometimes takes a bit longer to update issues.

Some systems (like WoD) use custom CSS classes to change the pause icon, which I can't predict since every system can use their own implementation and I can only address them specifically, when someone points them out to me.
I fixed the issue with WoD in 44b7af3d40af8bb3f4bfa1f1eb71750aa776a356 and I will push an update now.
